In [1]:
import os
import sys

import pandas as pd
from Bio import SeqIO

CURRENT_DIR = os.getcwd()
print(CURRENT_DIR)
our_data = CURRENT_DIR + "/../data/our_data/"

/home/hanxd/Repositories/ESP/Screening_and_application

In [2]:
# searchname = "Arabidopsis thaliana"
searchname = "Erigeron breviscapus"
# searchname = "Glycine max"
# searchname = 'Zea mays'


inputdir = our_data + "screening1/FunP450_All_06_new_Plant.fasta"
outputdir = our_data + f"screening2/{searchname}.fasta"

In [3]:
records = list(SeqIO.parse(inputdir, "fasta"))

In [4]:
df = pd.DataFrame(
    {
        "id": [rec.id for rec in records],
        "description": [rec.description for rec in records],
        "sequence": [str(rec.seq) for rec in records],
    }
)

In [5]:
df

,id,description,sequence
0,Viridiplantae_CYP51G1,Viridiplantae_CYP51G1 104_5_CYP51G;AT1G11680;o...,MELDSENKLLKTGLVIVATLVIAKLIFSFFTSDSKKKRLPPTLKAW...
1,Viridiplantae_CYP51G1Nt,Viridiplantae_CYP51G1Nt NtCYP51;Q8GZV0;Obtusif...,MELGDNKILNAGLLLVATLVVAKLISALIMPRSKKRLPPVIKSWPI...
2,Viridiplantae_CYP51G1Ps,Viridiplantae_CYP51G1Ps A0A0E3VN01;Obtusifolio...,MDVFDGNKFLNTVLLLITTIIVAKLISYFIIPKSKKRLPLILPGWP...
3,Viridiplantae_CYP51G1Sb,Viridiplantae_CYP51G1Sb P93846;Obtusifoliol [S...,MDLADIPQQQRLMAGLALVVATVIFLKLLLSFRSGGGKKRLPPTIP...
4,Viridiplantae_CYP51G1Sc,Viridiplantae_CYP51G1Sc Q673E9;Lanosterol|Obtu...,MELGDNKILNVGLLLVATLLVAKLISALIMPRSKKRLPPVIKALPI...
...,...,...,...
573,Viridiplantae_CYP98A6,Viridiplantae_CYP98A6 4-coumaroyl-4'-hydroxyph...,MALPAIPLAIIIFLIISYKLYQKLRLKLPPGPRPLPIIGNIYQVKP...
574,Viridiplantae_CYP98A8,Viridiplantae_CYP98A8 Tri-feruloyl-spermidine ...,MIIYLISLLPIIVATLMLYQRWWRSNIPPGPKPKFLLGNLHQMKPL...
575,Viridiplantae_CYP98A9,Viridiplantae_CYP98A9 Tri-coumaroyl-spermidine...,MDLLLISLTTIIIAAYMQNLRRRGSNIPPGPPTRFLVGNLHQLKPL...
576,Viridiplantae_CYP99A2,Viridiplantae_CYP99A2 syn-pimaradiene C19-oxid...,MQFFAKQNCQVNLLTNNPSSNPRFIMEINSAATLTLVSLLTLPILL...
577,Viridiplantae_CYP99A3,"Viridiplantae_CYP99A3 Q0JF01;9Beta-Pimara-7,15...",MMEINSEATVTLVSVVTLPILLALLTRKSSSKKRRPPGPWNLPLVG...

In [6]:
dfout = df[df["description"].str.contains(searchname)]

In [7]:
dfout

,id,description,sequence
28,Viridiplantae_CYP706X1,Viridiplantae_CYP706X1 601_7_EbreF6H;flavone 6...,MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPLPPGPKGLP...
299,Viridiplantae_CYP73A500,Viridiplantae_CYP73A500 601_2_C4H;cinnamate 4-...,MDLLLLEKTLIALFATIIITIIISKLRGKKFKLPPGPTAVPIFGNW...

In [8]:
with open(outputdir, "w") as file:
    for index, row in dfout.iterrows():
        id = row["id"]
        seq = row["sequence"]
        file.write(f">{id}\n{seq}\n")